[workspace]
members = [
    "butterfingersd-enroll",
    "butterfingersd-verify",
]
edition = "2021"
resolver = "2"

[workspace.dependencies]
libfprint-rs = "0.2.1"

[package]
name = "butterfingers"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = "1.12.0"
sqlx = { version = "0.7.2", features = ["runtime-async-std", "mysql", "macros", "time"] }
time = { version = "0.3.30", features = ["formatting", "macros"]}