[package]
name = "butterfingers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glib = "0.18.2"
libfprint-rs = "0.2.1"
sqlx = { version = "0.7.2", features = ["mysql"] }

[[bin]]
name = "butterfingersd-enroll"
path = "src/main.rs"
