[package]
name = "butterfingersd-verify"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glib = "0.18.2"
libfprint-rs = "0.2.1"

[[bin]]
name = "butterfingersd-verify"
path = "src/main.rs"